// AUTO-GENERATED by schema-gen — do not edit manually.
// Re-generate with: pnpm gen-types

export type AgentEvent =
  | { StepStarted: { label: string } }
  | { ToolCalled: { tool_name: string } }
  | { HumanApprovalRequired: { reason: string } }
  | { Finished: { status: string } };

export type AgentStatus = "Draft" | "Active" | "Archived";

export type RunStatus = "Pending" | "Running" | "WaitingForApproval" | "Succeeded" | "Failed";

export interface AgentConfig {
  description: string;
  id: string;
  name: string;
  status: AgentStatus;
  tenant_id: string;
}

export interface AgentRun {
  agent_id: string;
  id: string;
  status: RunStatus;
}

export interface AgentVersion {
  agent_id: string;
  id: string;
  snapshot_json: string;
  version: number;
}

export interface Permission {
  action: string;
  resource: string;
}

export interface RunStep {
  id: string;
  label: string;
  status: RunStatus;
}

export interface Tenant {
  id: string;
  name: string;
}

export interface ToolCall {
  arguments_json: string;
  tool_name: string;
}

export interface ToolResult {
  output_json: string;
  success: boolean;
  tool_name: string;
}

export interface ToolSchema {
  description: string;
  input_schema_json: string;
  name: string;
}

export interface User {
  email: string;
  id: string;
  tenant_id: string;
}

