// AUTO-GENERATED by schema-gen — do not edit manually.
// Re-generate with: pnpm gen-types

export type AgentEvent =
  | { ToolCalled: { args: unknown; tool: string } }
  | { HumanApprovalRequired: { action: string } }
  | { StepCompleted: { latency_ms: number; result: unknown } }
  | { RunFinished: { cost_usd: number } };

export type RunStatus = "Pending" | "Running" | "WaitingForApproval" | "Succeeded" | "Failed";

export type Trigger =
  | { Schedule: { cron: string } }
  | { Event: { event: string; source: string } };

export interface AgentConfig {
  id: string;
  name: string;
  steps: AgentStep[];
  trigger: Trigger;
}

export interface AgentRun {
  agent_id: string;
  id: string;
  status: RunStatus;
}

export interface AgentStep {
  id: string;
  name: string;
}

export interface AgentVersion {
  agent_id: string;
  id: string;
  snapshot_json: string;
  version: number;
}

export interface Permission {
  action: string;
  resource: string;
}

export interface RunStep {
  id: string;
  label: string;
  status: RunStatus;
}

export interface Tenant {
  id: string;
  name: string;
}

export interface ToolCall {
  arguments_json: string;
  tool_name: string;
}

export interface ToolResult {
  output_json: string;
  success: boolean;
  tool_name: string;
}

export interface ToolSchema {
  description: string;
  input_schema_json: string;
  name: string;
}

export interface User {
  email: string;
  id: string;
  tenant_id: string;
}

