use core_types::agent::{AgentConfig, AgentVersion};
use core_types::events::AgentEvent;
use core_types::run::{AgentRun, RunStatus, RunStep};
use core_types::tool::{ToolCall, ToolResult, ToolSchema};
use core_types::user::{Permission, Tenant, User};
use schemars::schema_for;
use serde_json::Value;
use std::collections::BTreeMap;

fn main() {
    let root_schemas = vec![
        serde_json::to_value(schema_for!(AgentConfig)).unwrap(),
        serde_json::to_value(schema_for!(AgentVersion)).unwrap(),
        serde_json::to_value(schema_for!(AgentRun)).unwrap(),
        serde_json::to_value(schema_for!(RunStep)).unwrap(),
        serde_json::to_value(schema_for!(RunStatus)).unwrap(),
        serde_json::to_value(schema_for!(ToolSchema)).unwrap(),
        serde_json::to_value(schema_for!(ToolCall)).unwrap(),
        serde_json::to_value(schema_for!(ToolResult)).unwrap(),
        serde_json::to_value(schema_for!(AgentEvent)).unwrap(),
        serde_json::to_value(schema_for!(User)).unwrap(),
        serde_json::to_value(schema_for!(Tenant)).unwrap(),
        serde_json::to_value(schema_for!(Permission)).unwrap(),
    ];

    // Collect all type definitions into a single map.
    // Each schema_for!() call produces a root schema with an optional `definitions` map.
    // We merge everything to deduplicate types like AgentStatus that appear in multiple roots.
    let mut defs: BTreeMap<String, Value> = BTreeMap::new();
    for root in &root_schemas {
        if let Some(definitions) = root.get("definitions").and_then(|d| d.as_object()) {
            for (name, schema) in definitions {
                defs.entry(name.clone()).or_insert_with(|| schema.clone());
            }
        }
        if let Some(title) = root.get("title").and_then(|t| t.as_str()) {
            defs.entry(title.to_string()).or_insert_with(|| root.clone());
        }
    }

    // Print header
    println!("// AUTO-GENERATED by schema-gen — do not edit manually.");
    println!("// Re-generate with: pnpm gen-types");

    // Emit type aliases (enums) first, then interfaces, so references resolve cleanly.
    let mut type_aliases = Vec::new();
    let mut interfaces = Vec::new();

    for (name, def) in &defs {
        if def.get("oneOf").is_some() || is_string_enum(def) {
            type_aliases.push((name, def));
        } else {
            interfaces.push((name, def));
        }
    }

    for (name, def) in &type_aliases {
        println!();
        print!("{}", convert_definition(name, def));
    }

    for (name, def) in &interfaces {
        println!();
        print!("{}", convert_definition(name, def));
    }

    // Trailing newline
    println!();
}

/// Converts a single JSON Schema definition to a TypeScript type declaration.
fn convert_definition(name: &str, def: &Value) -> String {
    // Handle plain string enum: { "type": "string", "enum": ["A", "B", "C"] }
    // schemars uses this for simple unit-variant enums.
    if is_string_enum(def) {
        let variants: Vec<String> = def
            .get("enum")
            .and_then(|e| e.as_array())
            .unwrap()
            .iter()
            .filter_map(|v| v.as_str().map(|s| format!("\"{}\"", s)))
            .collect();
        return format!("export type {} = {};\n", name, variants.join(" | "));
    }

    // Handle oneOf (enum types)
    if let Some(one_of) = def.get("oneOf").and_then(|o| o.as_array()) {
        let all_string_variants = one_of.iter().all(|v| {
            v.get("type").and_then(|t| t.as_str()) == Some("string")
                && v.get("enum")
                    .and_then(|e| e.as_array())
                    .map_or(false, |a| a.len() == 1)
        });

        if all_string_variants {
            // Simple string literal union: type Foo = "A" | "B" | "C";
            let variants: Vec<String> = one_of
                .iter()
                .filter_map(|v| {
                    v.get("enum")
                        .and_then(|e| e.as_array())
                        .and_then(|a| a.first())
                        .and_then(|s| s.as_str())
                        .map(|s| format!("\"{}\"", s))
                })
                .collect();
            return format!("export type {} = {};\n", name, variants.join(" | "));
        }

        // Externally-tagged enum with data (e.g. AgentEvent)
        let variants: Vec<String> = one_of
            .iter()
            .filter_map(|variant| {
                let props = variant.get("properties")?.as_object()?;
                let (tag_name, inner_schema) = props.iter().next()?;
                let inner = convert_object_inline(inner_schema);
                Some(format!("  | {{ {}: {} }}", tag_name, inner))
            })
            .collect();
        return format!("export type {} =\n{};\n", name, variants.join("\n"));
    }

    // Struct -> interface
    if let Some(properties) = def.get("properties").and_then(|p| p.as_object()) {
        let required: Vec<&str> = def
            .get("required")
            .and_then(|r| r.as_array())
            .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();

        let fields: Vec<String> = properties
            .iter()
            .map(|(field_name, field_schema)| {
                let ts_type = resolve_ts_type(field_schema);
                let opt = if required.contains(&field_name.as_str()) {
                    ""
                } else {
                    "?"
                };
                format!("  {}{}: {};", field_name, opt, ts_type)
            })
            .collect();

        return format!("export interface {} {{\n{}\n}}\n", name, fields.join("\n"));
    }

    format!("// Could not convert: {}\n", name)
}

/// Checks if a JSON Schema represents a plain string enum.
fn is_string_enum(def: &Value) -> bool {
    def.get("type").and_then(|t| t.as_str()) == Some("string")
        && def.get("enum").and_then(|e| e.as_array()).is_some()
}

/// Converts an inline JSON Schema object to a TypeScript object literal type.
fn convert_object_inline(schema: &Value) -> String {
    if let Some(properties) = schema.get("properties").and_then(|p| p.as_object()) {
        let required: Vec<&str> = schema
            .get("required")
            .and_then(|r| r.as_array())
            .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();

        let fields: Vec<String> = properties
            .iter()
            .map(|(name, field_schema)| {
                let ts_type = resolve_ts_type(field_schema);
                let opt = if required.contains(&name.as_str()) {
                    ""
                } else {
                    "?"
                };
                format!("{}{}: {}", name, opt, ts_type)
            })
            .collect();

        return format!("{{ {} }}", fields.join("; "));
    }
    "unknown".to_string()
}

/// Maps a JSON Schema type reference to a TypeScript type string.
fn resolve_ts_type(schema: &Value) -> String {
    // Handle $ref
    if let Some(ref_path) = schema.get("$ref").and_then(|r| r.as_str()) {
        return ref_path.rsplit('/').next().unwrap_or("unknown").to_string();
    }

    // Handle allOf with a single $ref (schemars sometimes wraps refs in allOf)
    if let Some(all_of) = schema.get("allOf").and_then(|a| a.as_array()) {
        if all_of.len() == 1 {
            return resolve_ts_type(&all_of[0]);
        }
    }

    match schema.get("type").and_then(|t| t.as_str()) {
        Some("string") => "string".to_string(),
        Some("integer") | Some("number") => "number".to_string(),
        Some("boolean") => "boolean".to_string(),
        Some("array") => {
            let items_type = schema
                .get("items")
                .map(|i| resolve_ts_type(i))
                .unwrap_or_else(|| "unknown".to_string());
            format!("{}[]", items_type)
        }
        Some("object") => {
            if schema
                .get("properties")
                .and_then(|p| p.as_object())
                .is_some()
            {
                return convert_object_inline(schema);
            }
            "Record<string, unknown>".to_string()
        }
        _ => "unknown".to_string(),
    }
}
