use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Describes a persisted agent configuration contract.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct AgentConfig {
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub name: String,
    pub description: String,
    pub status: AgentStatus,
}

/// Represents the lifecycle state of an agent definition.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub enum AgentStatus {
    Draft,
    Active,
    Archived,
}

/// Captures a versioned snapshot of agent behavior.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct AgentVersion {
    pub id: Uuid,
    pub agent_id: Uuid,
    pub version: i32,
    pub snapshot_json: String,
}

/// Returns a scaffolded example agent config for tests, previews, or schema generation.
///
/// This helper exists so downstream crates have a stable, typed seed object while
/// business logic is still unimplemented.
pub fn sample_agent_config() -> AgentConfig {
    AgentConfig {
        id: Uuid::nil(),
        tenant_id: Uuid::nil(),
        name: "Example Agent".to_string(),
        description: "Placeholder agent configuration generated by the scaffold.".to_string(),
        status: AgentStatus::Draft,
    }
}
